version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

  mailcatcher:
    image: zolweb/docker-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
